### ISSUE TITLE
ErrorException: Template error: [E_USER_WARNING] Cannot call method canReply on a non-object (NULL)

### ISSUE THREAD

**Issue by xfsites** [021-projects/xenforo-messenger#3]
```
ErrorException: Template error: [E_USER_WARNING] Cannot call method canReply on a non-object (NULL) src/XF/Template/Templater.php:1179
Generated by: xfuser Sep 13, 2023 at 1:21 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, '[E_USER_WARNING...', '/var/www/xf...', 1179)
#1 src/XF/Template/Templater.php(1179): trigger_error('Cannot call met...', 512)
#2 internal_data/code_cache/templates/l1/s13/public/xf_messenger_chat_macros.php(490): XF\Template\Templater->method(NULL, 'canReply', Array)
#3 src/XF/Template/Templater.php(827): XF\Template\Templater->{closure}(Object(xenMade\TPM\XF\Template\Templater), Array, NULL)
#4 src/addons/MaZ/AMP/XF/Template/Templater.php(152): XF\Template\Templater->callMacro('xf_messenger_ch...', 'room', Array, Array, Object(XF\Template\MacroState))
#5 internal_data/code_cache/templates/l1/s13/public/xf_messenger_chat_macros.php(462): MaZ\AMP\XF\Template\TemplaterAbstract->callMacro(NULL, 'room', Array, Array)
#6 src/XF/Template/Templater.php(827): XF\Template\Templater->{closure}(Object(xenMade\TPM\XF\Template\Templater), Array, NULL)
#7 src/addons/MaZ/AMP/XF/Template/Templater.php(152): XF\Template\Templater->callMacro('xf_messenger_ch...', 'rooms', Array, Array, Object(XF\Template\MacroState))
#8 internal_data/code_cache/templates/l1/s13/public/xf_messenger_rooms.php(9): MaZ\AMP\XF\Template\TemplaterAbstract->callMacro('xf_messenger_ch...', 'rooms', Array, Array)
#9 src/XF/Template/Templater.php(1654): XF\Template\Templater->{closure}(Object(xenMade\TPM\XF\Template\Templater), Array, NULL)
#10 src/addons/MaZ/AMP/Traits/Templater/XF22.php(52): XF\Template\Templater->renderTemplate('xf_messenger_ro...', Array, true, NULL)
#11 src/XF/Template/Template.php(24): MaZ\AMP\XF\Template\Templater->renderTemplate('public:xf_messe...', Array)
#12 src/XF/Mvc/Renderer/Json.php(86): XF\Template\Template->render()
#13 src/XF/Mvc/Renderer/Json.php(70): XF\Mvc\Renderer\Json->renderHtmlFallback('BS\\XFMessenger:...', 'public:xf_messe...', Array)
#14 src/XF/Mvc/Dispatcher.php(460): XF\Mvc\Renderer\Json->renderView('BS\\XFMessenger:...', 'public:xf_messe...', Array)
#15 src/XF/Mvc/Dispatcher.php(442): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#16 src/XF/Mvc/Dispatcher.php(402): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#17 src/XF/Mvc/Dispatcher.php(60): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#18 src/XF/App.php(2487): XF\Mvc\Dispatcher->run()
#19 src/XF.php(524): XF\App->run()
#20 index.php(20): XF::runApp('XF\\Pub\\App')
#21 {main}
Request state
array(4) {
  ["url"] => string(269) "/conversations/messenger/rooms?filter%5Baround_room_tag%5D=&filter%5BwithListInfo%5D=true&_xfRequestUri=%2Fconversations%2Fmessenger%2F%3Fc%5Bto%5D%3Duser2%26c%5Bopen%5D%3D1&_xfWithData=1&_xfToken=1694582479%2C8e91ee27726b239632937b9c50c5f4bb&_xfResponseType=json"
  ["referrer"] => string(73) "https://xf.com/conversations/messenger/?c[to]=user2&c[open]=1"
  ["_GET"] => array(6) {
    ["/conversations/messenger/rooms"] => string(0) ""
    ["filter"] => array(2) {
      ["around_room_tag"] => string(0) ""
      ["withListInfo"] => string(4) "true"
    }
    ["_xfRequestUri"] => string(53) "/conversations/messenger/?c[to]=user2&c[open]=1"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1694582479,8e91ee27726b239632937b9c50c5f4bb"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}



ErrorException: Template error: [E_USER_WARNING] Cannot call method canReply on a non-object (NULL) src/XF/Template/Templater.php:1179
Generated by: xfuser Sep 13, 2023 at 9:23 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, '[E_USER_WARNING...', '/var/www/xf...', 1179)
#1 src/XF/Template/Templater.php(1179): trigger_error('Cannot call met...', 512)
#2 internal_data/code_cache/templates/l1/s13/public/xf_messenger_chat_macros.php(490): XF\Template\Templater->method(NULL, 'canReply', Array)
#3 src/XF/Template/Templater.php(827): XF\Template\Templater->{closure}(Object(xenMade\TPM\XF\Template\Templater), Array, NULL)
#4 src/addons/MaZ/AMP/XF/Template/Templater.php(152): XF\Template\Templater->callMacro('xf_messenger_ch...', 'room', Array, Array, Object(XF\Template\MacroState))
#5 internal_data/code_cache/templates/l1/s13/public/xf_messenger_chat_macros.php(462): MaZ\AMP\XF\Template\TemplaterAbstract->callMacro(NULL, 'room', Array, Array)
#6 src/XF/Template/Templater.php(827): XF\Template\Templater->{closure}(Object(xenMade\TPM\XF\Template\Templater), Array, NULL)
#7 src/addons/MaZ/AMP/XF/Template/Templater.php(152): XF\Template\Templater->callMacro('xf_messenger_ch...', 'rooms', Array, Array, Object(XF\Template\MacroState))
#8 internal_data/code_cache/templates/l1/s13/public/xf_messenger_rooms.php(9): MaZ\AMP\XF\Template\TemplaterAbstract->callMacro('xf_messenger_ch...', 'rooms', Array, Array)
#9 src/XF/Template/Templater.php(1654): XF\Template\Templater->{closure}(Object(xenMade\TPM\XF\Template\Templater), Array, NULL)
#10 src/addons/MaZ/AMP/Traits/Templater/XF22.php(52): XF\Template\Templater->renderTemplate('xf_messenger_ro...', Array, true, NULL)
#11 src/XF/Template/Template.php(24): MaZ\AMP\XF\Template\Templater->renderTemplate('public:xf_messe...', Array)
#12 src/XF/Mvc/Renderer/Json.php(86): XF\Template\Template->render()
#13 src/XF/Mvc/Renderer/Json.php(70): XF\Mvc\Renderer\Json->renderHtmlFallback('BS\\XFMessenger:...', 'public:xf_messe...', Array)
#14 src/XF/Mvc/Dispatcher.php(460): XF\Mvc\Renderer\Json->renderView('BS\\XFMessenger:...', 'public:xf_messe...', Array)
#15 src/XF/Mvc/Dispatcher.php(442): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#16 src/XF/Mvc/Dispatcher.php(402): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#17 src/XF/Mvc/Dispatcher.php(60): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#18 src/XF/App.php(2487): XF\Mvc\Dispatcher->run()
#19 src/XF.php(524): XF\App->run()
#20 index.php(20): XF::runApp('XF\\Pub\\App')
#21 {main}
Request state
array(4) {
  ["url"] => string(268) "/conversations/messenger/rooms?filter%5Baround_room_tag%5D=&filter%5BwithListInfo%5D=true&_xfRequestUri=%2Fconversations%2Fmessenger%2F%3Fc%5Bto%5D%3Duser1%26c%5Bopen%5D%3D1&_xfWithData=1&_xfToken=1694611382%2C45c341cf0c29e617c65702831e2663b4&_xfResponseType=json"
  ["referrer"] => string(72) "https://xf.com/conversations/messenger/?c[to]=user1&c[open]=1"
  ["_GET"] => array(6) {
    ["/conversations/messenger/rooms"] => string(0) ""
    ["filter"] => array(2) {
      ["around_room_tag"] => string(0) ""
      ["withListInfo"] => string(4) "true"
    }
    ["_xfRequestUri"] => string(52) "/conversations/messenger/?c[to]=user1&c[open]=1"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1694611382,45c341cf0c29e617c65702831e2663b4"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}

```

**Comment by xfsites** [comment]
Using PHP 8.1

**Comment by 021-projects** [comment]
Hello. This issue has already been discussed.

> Based on the latest error, one of the entries in xf_conversation_user does not have an associated entry in xf_conversation_master. This is not normal and probably not related to the messenger, since it does not interfere with such processes, but only creates a wrapper for the existing functionality.
To find similar records, run a database query:
```
select * from xf_conversation_user as userConv
left join xf_conversation_master as conv
on conv.conversation_id = userConv.conversation_id
where conv.conversation_id is null
```
